[CCXDEV-12258] New engine for Archive Sync service
RedHatInsights/insights-ccx-messaging pull request #164
Opened 2024-03-15 09:53 UTC by Jakub007d

# Description

Added new engine and uploader for sync service.

Fixes [CCXDEV-12258](https://issues.redhat.com/browse/CCXDEV-12258)

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update
- Unit tests (no changes in the code)

## Testing steps

Tested locally.

## Checklist
* [ ] `pre-commit run -a` passes
* [ ] updated documentation wherever necessary
* [ ] added or modified tests if necessary
* [ ] updated schemas and validators in [insights-data-schemas](https://github.com/RedHatInsights/insights-data-schemas) in case of input/output change

2024-03-15 11:32 UTC, joselsegura requested changes

2024-03-18 10:15 UTC, joselsegura approved these changes

2024-03-18 11:14 UTC, epapbak commented on ccx_messaging/engines/s3_upload_engine.py
> +    target_path = (
nitpick: probably better to format one string than doing this concatenation

2024-03-18 11:14 UTC, epapbak approved these changes

2024-03-18 11:59 UTC, merged